/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admingui_eatandhear;

import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tim
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        deleteMenu = new javax.swing.JMenuItem();
        saveChangesMenu = new javax.swing.JMenuItem();
        flagPopup = new javax.swing.JPopupMenu();
        flagDeleteMenu = new javax.swing.JMenuItem();
        flagSaveChangeMenu = new javax.swing.JMenuItem();
        mainTabbedPane = new javax.swing.JTabbedPane();
        entriesPane = new javax.swing.JPanel();
        loadEntriesButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        entriesTable = new javax.swing.JTable();
        commentsPane = new javax.swing.JPanel();
        flaggedEntriesPane = new javax.swing.JScrollPane();
        flaggedEntriesTable = new javax.swing.JTable();
        loadFlaggedEntriesButton = new javax.swing.JButton();
        statusPane = new javax.swing.JPanel();
        loadStatusButton = new javax.swing.JButton();
        uptimeLabel = new javax.swing.JLabel();
        connectedLabel = new javax.swing.JLabel();
        dbEntriesLabel = new javax.swing.JLabel();
        flaggedEntriesLabel = new javax.swing.JLabel();
        userAdminpane = new javax.swing.JPanel();
        addNewCommentPane = new javax.swing.JPanel();
        addNewComment = new javax.swing.JButton();
        clearCommentPanel = new javax.swing.JButton();
        restIdField = new javax.swing.JTextField();
        userNameField = new javax.swing.JTextField();
        userIdField = new javax.swing.JTextField();
        rIdLabel = new javax.swing.JLabel();
        uNameLabel = new javax.swing.JLabel();
        uIdLabel = new javax.swing.JLabel();
        commentLabel = new javax.swing.JLabel();
        soundLvlLabel = new javax.swing.JLabel();
        soundLvlField = new javax.swing.JTextField();
        commentField = new javax.swing.JTextField();

        popup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popupMouseClicked(evt);
            }
        });
        popup.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                popupPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        popup.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                popupMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });

        deleteMenu.setText("Delete");
        deleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuActionPerformed(evt);
            }
        });
        popup.add(deleteMenu);

        saveChangesMenu.setText("Save");
        saveChangesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesMenuActionPerformed(evt);
            }
        });
        popup.add(saveChangesMenu);

        flagPopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flagPopupMouseClicked(evt);
            }
        });
        flagPopup.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                flagPopupPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        flagPopup.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                flagPopupMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });

        flagDeleteMenu.setText("Delete");
        flagDeleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagDeleteMenuActionPerformed(evt);
            }
        });
        flagPopup.add(flagDeleteMenu);

        flagSaveChangeMenu.setText("Save");
        flagSaveChangeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagSaveChangeMenuActionPerformed(evt);
            }
        });
        flagPopup.add(flagSaveChangeMenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadEntriesButton.setText("Get entries");
        loadEntriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadEntriesButtonActionPerformed(evt);
            }
        });

        entriesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        entriesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                entriesTableMouseReleased(evt);
            }
        });
        tableScrollPane.setViewportView(entriesTable);

        javax.swing.GroupLayout entriesPaneLayout = new javax.swing.GroupLayout(entriesPane);
        entriesPane.setLayout(entriesPaneLayout);
        entriesPaneLayout.setHorizontalGroup(
            entriesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entriesPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entriesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entriesPaneLayout.createSequentialGroup()
                        .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(entriesPaneLayout.createSequentialGroup()
                        .addComponent(loadEntriesButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        entriesPaneLayout.setVerticalGroup(
            entriesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entriesPaneLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(loadEntriesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Entries", entriesPane);

        flaggedEntriesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        flaggedEntriesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                flaggedEntriesTableMouseReleased(evt);
            }
        });
        flaggedEntriesPane.setViewportView(flaggedEntriesTable);

        loadFlaggedEntriesButton.setText("Load comments");
        loadFlaggedEntriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFlaggedEntriesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout commentsPaneLayout = new javax.swing.GroupLayout(commentsPane);
        commentsPane.setLayout(commentsPaneLayout);
        commentsPaneLayout.setHorizontalGroup(
            commentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commentsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flaggedEntriesPane, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addGroup(commentsPaneLayout.createSequentialGroup()
                        .addComponent(loadFlaggedEntriesButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        commentsPaneLayout.setVerticalGroup(
            commentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commentsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadFlaggedEntriesButton)
                .addGap(14, 14, 14)
                .addComponent(flaggedEntriesPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Flagged comments", commentsPane);

        loadStatusButton.setText("Get status");

        uptimeLabel.setText("Uptime:");

        connectedLabel.setText("Connected:");

        dbEntriesLabel.setText("Database entries:");

        flaggedEntriesLabel.setText("Flagged comments:");

        javax.swing.GroupLayout statusPaneLayout = new javax.swing.GroupLayout(statusPane);
        statusPane.setLayout(statusPaneLayout);
        statusPaneLayout.setHorizontalGroup(
            statusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadStatusButton)
                    .addComponent(uptimeLabel)
                    .addComponent(connectedLabel)
                    .addComponent(dbEntriesLabel)
                    .addComponent(flaggedEntriesLabel))
                .addContainerGap(554, Short.MAX_VALUE))
        );
        statusPaneLayout.setVerticalGroup(
            statusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPaneLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(loadStatusButton)
                .addGap(32, 32, 32)
                .addComponent(uptimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbEntriesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flaggedEntriesLabel)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Status", statusPane);

        javax.swing.GroupLayout userAdminpaneLayout = new javax.swing.GroupLayout(userAdminpane);
        userAdminpane.setLayout(userAdminpaneLayout);
        userAdminpaneLayout.setHorizontalGroup(
            userAdminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );
        userAdminpaneLayout.setVerticalGroup(
            userAdminpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("User admin", userAdminpane);

        addNewComment.setText("Add");
        addNewComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCommentActionPerformed(evt);
            }
        });

        clearCommentPanel.setText("Clear");
        clearCommentPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCommentPanelActionPerformed(evt);
            }
        });

        restIdField.setPreferredSize(new java.awt.Dimension(70, 20));

        userNameField.setPreferredSize(new java.awt.Dimension(70, 20));

        userIdField.setPreferredSize(new java.awt.Dimension(70, 20));

        rIdLabel.setText("Restaurant ID:");

        uNameLabel.setText("Username:");

        uIdLabel.setText("User ID: ");

        commentLabel.setText("Comment:");

        soundLvlLabel.setText("Soundlevel:");

        soundLvlField.setPreferredSize(new java.awt.Dimension(70, 20));

        commentField.setPreferredSize(new java.awt.Dimension(70, 20));

        javax.swing.GroupLayout addNewCommentPaneLayout = new javax.swing.GroupLayout(addNewCommentPane);
        addNewCommentPane.setLayout(addNewCommentPaneLayout);
        addNewCommentPaneLayout.setHorizontalGroup(
            addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewCommentPaneLayout.createSequentialGroup()
                .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(commentLabel)
                    .addComponent(soundLvlLabel)
                    .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addNewCommentPaneLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(addNewComment))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewCommentPaneLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(rIdLabel)))
                            .addComponent(uNameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(uIdLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearCommentPanel)
                    .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soundLvlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        addNewCommentPaneLayout.setVerticalGroup(
            addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewCommentPaneLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commentLabel)
                    .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soundLvlLabel)
                    .addComponent(soundLvlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(addNewCommentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewComment)
                    .addComponent(clearCommentPanel))
                .addGap(100, 100, 100))
        );

        mainTabbedPane.addTab("Add new comment", addNewCommentPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadEntriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadEntriesButtonActionPerformed

        Mongo mongo = new Mongo();

        entriesTable.setModel(mongo.getComments());

    }//GEN-LAST:event_loadEntriesButtonActionPerformed

    private void addNewCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCommentActionPerformed

        Mongo mongo = new Mongo();
        if (mongo.insertComment(new Comment(restIdField.getText(), userIdField.getText(), userNameField.getText(), soundLvlField.getText(), commentField.getText()))) {

            System.out.println("Added succesfully.");
        } else {
            System.out.println("Something went wrong :-C");
        }



    }//GEN-LAST:event_addNewCommentActionPerformed

    private void clearCommentPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCommentPanelActionPerformed


        restIdField.setText("");
        userIdField.setText("");
        userNameField.setText("");
        soundLvlField.setText("");
        commentField.setText("");

    }//GEN-LAST:event_clearCommentPanelActionPerformed

    private void entriesTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entriesTableMouseReleased

        if (evt.isPopupTrigger()) {

            JTable source = (JTable) evt.getSource();
            int row = source.rowAtPoint(evt.getPoint());
            int column = source.columnAtPoint(evt.getPoint());

            if (!source.isRowSelected(row)) {
                source.changeSelection(row, column, false, false);
            }

            popup.show(evt.getComponent(), evt.getX(), evt.getY());
        }

    }//GEN-LAST:event_entriesTableMouseReleased

    private void deleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuActionPerformed


        Mongo mongo = new Mongo();

        mongo.deleteComment((String) entriesTable.getValueAt(entriesTable.getSelectedRow(), 0), (String) entriesTable.getValueAt(entriesTable.getSelectedRow(), 2), (String) entriesTable.getValueAt(entriesTable.getSelectedRow(), 3));



    }//GEN-LAST:event_deleteMenuActionPerformed

    private void popupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupMouseClicked
    }//GEN-LAST:event_popupMouseClicked

    private void popupPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_popupPopupMenuWillBecomeInvisible
    }//GEN-LAST:event_popupPopupMenuWillBecomeInvisible

    private void popupMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_popupMenuKeyPressed
    }//GEN-LAST:event_popupMenuKeyPressed

    private void saveChangesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesMenuActionPerformed
      
        
      
       Mongo mongo = new Mongo();
       DefaultTableModel old = mongo.getComments();
  
       String rId =  (String) entriesTable.getValueAt(entriesTable.getSelectedRow(), 0);
       String uId  = (String) entriesTable.getValueAt(entriesTable.getSelectedRow(), 2);
       String uName = (String) entriesTable.getValueAt(entriesTable.getSelectedRow(), 1);
       String soundLvl = (String)entriesTable.getValueAt(entriesTable.getSelectedRow(), 4);
       String text = (String) entriesTable.getValueAt(entriesTable.getSelectedRow(), 3);
       
       String old_rId =  (String) old.getValueAt(entriesTable.getSelectedRow(), 0);
       String old_uId  = (String) old.getValueAt(entriesTable.getSelectedRow(), 2);
       String old_uName = (String) old.getValueAt(entriesTable.getSelectedRow(), 1);
       String old_soundLvl = (String) old.getValueAt(entriesTable.getSelectedRow(), 4);
       String old_text = (String) old.getValueAt(entriesTable.getSelectedRow(), 3);
      
       
       Comment comment = new Comment(rId, uId, uName, soundLvl, text);
       Comment oldComment = new Comment(old_rId, old_uId, old_uName, old_soundLvl, old_text);  
      
        mongo.saveChanges(comment, oldComment);
        
    }//GEN-LAST:event_saveChangesMenuActionPerformed

    private void loadFlaggedEntriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFlaggedEntriesButtonActionPerformed
       
        Mongo mongo = new Mongo();

        flaggedEntriesTable.setModel(mongo.getFlaggedComments());
        
    }//GEN-LAST:event_loadFlaggedEntriesButtonActionPerformed

    private void flaggedEntriesTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flaggedEntriesTableMouseReleased
       
             if (evt.isPopupTrigger()) {

            JTable source = (JTable) evt.getSource();
            int row = source.rowAtPoint(evt.getPoint());
            int column = source.columnAtPoint(evt.getPoint());

            if (!source.isRowSelected(row)) {
                source.changeSelection(row, column, false, false);
            }

            flagPopup.show(evt.getComponent(), evt.getX(), evt.getY());
        }
        
    }//GEN-LAST:event_flaggedEntriesTableMouseReleased

    private void flagDeleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagDeleteMenuActionPerformed
           Mongo mongo = new Mongo();

        mongo.deleteComment((String) flaggedEntriesTable.getValueAt(flaggedEntriesTable.getSelectedRow(), 0), (String) flaggedEntriesTable.getValueAt(flaggedEntriesTable.getSelectedRow(), 2), (String) flaggedEntriesTable.getValueAt(flaggedEntriesTable.getSelectedRow(), 3));
    }//GEN-LAST:event_flagDeleteMenuActionPerformed

    private void flagSaveChangeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagSaveChangeMenuActionPerformed
        
             
       Mongo mongo = new Mongo();
       DefaultTableModel old = mongo.getFlaggedComments();
  
       String rId =  (String) flaggedEntriesTable.getValueAt(flaggedEntriesTable.getSelectedRow(), 0);
       String uId  = (String) flaggedEntriesTable.getValueAt(flaggedEntriesTable.getSelectedRow(), 2);
       String uName = (String) flaggedEntriesTable.getValueAt(flaggedEntriesTable.getSelectedRow(), 1);
       String soundLvl = (String)flaggedEntriesTable.getValueAt(flaggedEntriesTable.getSelectedRow(), 4);
       String text = (String) flaggedEntriesTable.getValueAt(flaggedEntriesTable.getSelectedRow(), 3);
       
       String old_rId =  (String) old.getValueAt(flaggedEntriesTable.getSelectedRow(), 0);
       String old_uId  = (String) old.getValueAt(flaggedEntriesTable.getSelectedRow(), 2);
       String old_uName = (String) old.getValueAt(flaggedEntriesTable.getSelectedRow(), 1);
       String old_soundLvl = (String) old.getValueAt(flaggedEntriesTable.getSelectedRow(), 4);
       String old_text = (String) old.getValueAt(flaggedEntriesTable.getSelectedRow(), 3);
      
       
       Comment comment = new Comment(rId, uId, uName, soundLvl, text);
       Comment oldComment = new Comment(old_rId, old_uId, old_uName, old_soundLvl, old_text);  
      
        mongo.saveChanges(comment, oldComment);
        
    }//GEN-LAST:event_flagSaveChangeMenuActionPerformed

    private void flagPopupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flagPopupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_flagPopupMouseClicked

    private void flagPopupPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_flagPopupPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_flagPopupPopupMenuWillBecomeInvisible

    private void flagPopupMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_flagPopupMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_flagPopupMenuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewComment;
    private javax.swing.JPanel addNewCommentPane;
    private javax.swing.JButton clearCommentPanel;
    private javax.swing.JTextField commentField;
    private javax.swing.JLabel commentLabel;
    private javax.swing.JPanel commentsPane;
    private javax.swing.JLabel connectedLabel;
    private javax.swing.JLabel dbEntriesLabel;
    private javax.swing.JMenuItem deleteMenu;
    private javax.swing.JPanel entriesPane;
    private javax.swing.JTable entriesTable;
    private javax.swing.JMenuItem flagDeleteMenu;
    private javax.swing.JPopupMenu flagPopup;
    private javax.swing.JMenuItem flagSaveChangeMenu;
    private javax.swing.JLabel flaggedEntriesLabel;
    private javax.swing.JScrollPane flaggedEntriesPane;
    private javax.swing.JTable flaggedEntriesTable;
    private javax.swing.JButton loadEntriesButton;
    private javax.swing.JButton loadFlaggedEntriesButton;
    private javax.swing.JButton loadStatusButton;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JLabel rIdLabel;
    private javax.swing.JTextField restIdField;
    private javax.swing.JMenuItem saveChangesMenu;
    private javax.swing.JTextField soundLvlField;
    private javax.swing.JLabel soundLvlLabel;
    private javax.swing.JPanel statusPane;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel uIdLabel;
    private javax.swing.JLabel uNameLabel;
    private javax.swing.JLabel uptimeLabel;
    private javax.swing.JPanel userAdminpane;
    private javax.swing.JTextField userIdField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
